apiVersion: v1
kind: Service
metadata:
  namespace: breadbook
  name: frontend-svc
spec:
  selector:
    type: frontend
    deployment: front-COLOR
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer