apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: breadbook
spec:
  selector:
    type: backend
    deployment: blue # 최초 배포 시 blue로 시작, 이후 Jenkins에서 patch로 전환
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP