pipeline {
    agent none  // 기본적으로 마스터에서 실행하지 않음

    environment {
        IMAGE_NAME = 'iuch/breadbook-front'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Git Clone') {
            agent { label 'build' }  // 빌드 전용 Agent에서 실행
            steps{
                echo "Cloneing Repository"
                git branch: 'main', url: 'https://github.com/beyond-sw-camp/be12-2nd-5ven-bread_book'
            }
        }
        stage('Npm Run Build') {
            agent { label 'build' }  // 빌드 전용 Agent에서 실행
            steps{
                echo "install"
                sh 'npm install'

                echo "Build"
                sh 'npm run build'
            }
        }
        stage('Build Docker Image') {
            agent { label 'build' }  // 빌드 전용 Agent에서 실행
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                }
            }
        }
        stage('Push to Registry') {
            agent { label 'build' }  // 빌드 전용 Agent에서 실행
            steps {
                script {
                    withDockerRegistry([credentialsId: 'DOCKER_HUB']) {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                    }
                }
            }
        }
        // stage('Deploy') {
        //     agent { label 'deploy' }  // 배포 전용 Agent에서 실행
        //     steps {
        //         // 배포 관련 작업
        //     }
        // }
        stage('SSH') {
            agent { label 'deploy' }
            steps{
                script{
                    def color      = (BUILD_NUMBER.toInteger() % 2 == 0) ? 'green' : 'blue'
                    def otherColor = (color == 'green') ? 'blue' : 'green'
                    sshPublisher(
                        publishers: [
                            sshPublisherDesc(
                                configName: 'k8s',
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        sourceFiles: 'k8s/frontend-deployment.yml, k8s/frontend-external-service.yml',
                                        remoteDirectory: '/ciu',
                                        execCommand: """
                                            sed -i "s/LATEST/$BUILD_ID/g" /home/test/ciu/k8s/frontend-deployment.yml
                                            sed -i "s/COLOR/$color/g" /home/test/ciu/k8s/frontend-deployment.yml
                                            sed -i "s/COLOR/$color/g" /home/test/ciu/k8s/frontend-external-service.yml
                                        """
                                    ),
                                    sshTransfer(
                                        execCommand: """
                                            kubectl apply -f /home/test/ciu/k8s/frontend-deployment.yml
                                            kubectl rollout status deployment/backend-deployment-$color -n breadbook --timeout=120s
                                            kubectl apply -f /home/test/ciu/k8s/frontend-external-service.yml
                                            kubectl scale deployment/frontend-deployment-$otherColor -n breadbook --replicas=0 || true
                                        """
                                    )
                                ]
                            )
                        ]
                    )
                }
            }
        }
    }
 }
